/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#1e1f25',
        'primary-fixed-dim': '#ffb956',
        'primary-container': '#f2a93b',
        'on-tertiary-fixed-variant': '#793100',
        surface: '#111318',
        'surface-container-lowest': '#0c0e13',
        'on-primary-fixed-variant': '#633f00',
        'error-container': '#93000a',
        'surface-container-highest': '#33353a',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#b3b5bd',
        'primary-fixed': '#ffddb5',
        primary: '#ffca85',
        'secondary-container': '#44474e',
        'on-primary-container': '#664000',
        'surface-container-high': '#282a2f',
        'surface-tint': '#ffb956',
        'on-primary': '#452b00',
        'inverse-primary': '#835400',
        'inverse-on-surface': '#2e3036',
        'tertiary-container': '#ffa06f',
        secondary: '#c4c6cf',
        'on-background': '#e2e2e9',
        'inverse-surface': '#e2e2e9',
        'surface-bright': '#37393f',
        tertiary: '#ffc7ad',
        'on-surface-variant': '#d6c3af',
        'secondary-fixed': '#e1e2eb',
        'on-tertiary-fixed': '#341100',
        'secondary-fixed-dim': '#c4c6cf',
        'on-tertiary-container': '#7c3200',
        'outline-variant': '#514535',
        'on-primary-fixed': '#2a1800',
        outline: '#9e8e7c',
        error: '#ffb4ab',
        'tertiary-fixed': '#ffdbcb',
        'on-surface': '#e2e2e9',
        'on-secondary-fixed-variant': '#44474e',
        'on-secondary': '#2d3037',
        'surface-dim': '#111318',
        'on-secondary-fixed': '#191c22',
        background: '#111318',
        'on-tertiary': '#552000',
        'on-error': '#690005',
        'tertiary-fixed-dim': '#ffb692',
        'surface-variant': '#33353a',
        'surface-container-low': '#1a1b21',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-mobile': '48px',
        xs: '4px',
        md: '16px',
        unit: '4px',
        'section-desktop': '96px',
        'max-width': '1200px',
        lg: '24px',
        sm: '8px',
        xl: '32px',
      },
      fontFamily: {
        'headline-md': ['Space Grotesk', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['31px', { lineHeight: '1.2', fontWeight: '600' }],
        display: ['49px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['39px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-mono': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      maxWidth: {
        'max-width': '1200px',
      },
    },
  },
  plugins: [],
};
