apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: vigil-frontend-config
  namespace: vigil
spec:
  redirectToHttps:
    enabled: false
    responseCodeName: MOVED_PERMANENTLY_DEFAULT # 301 Redirect
    